### ISSUE TITLE
documentation should talk about tree_idx in multi-comp models

### ISSUE THREAD

**Issue by luadam4c** [sg-s/xolotl#302] opened 2018-12-14 04:02 UTC
I realized that if I only clamp the soma and not the dendrites (i.e., leave the V_clamp setting for dendrites as NaN), the currents in the dendrites goes to **infinity**, which is not physiological. 

I know in large invertebrates axons two-electrode voltage clamp is often performed. That's probably why you set the voltage clamp option to work that way. However, in mammalian neurons one usually performs a whole cell patch clamp, which is a single electrode voltage clamp. Therefore, I don't think it is safe to assume that the voltage is constant throughout the cell. You basically need to inject enough current to account for the entire surface area of the cell.

That's how NEURON works too. You can place an IClamp or a VClamp at a particular position in a particular compartment.

**Comment by luadam4c** [comment] 2018-12-14 04:47
Actually I'm not sure this was the issue. I'm having trouble converging whenever [this syntax](https://xolotl.readthedocs.io/en/master/tutorials/first-neuron/#adding-channels-to-our-compartment) is used:

```{matlab}
x.soma.add('Leak', 'gbar', gLeak, 'E', eLeak);
```

But it converges when [this syntax](https://xolotl.readthedocs.io/en/master/reference/xolotl-methods/#add) is used:

```{matlab}
x.soma.add('conductance', 'Leak', 'gbar', gLeak, 'E', eLeak);
```

Perhaps I just don't understand how your Leak channel works ...

**Comment by luadam4c** [comment] 2018-12-14 04:54
I just realized that your Leak channel does not pass current.

![test_voltage_clamp2](https://user-images.githubusercontent.com/36715881/49983708-5556ce00-ff32-11e8-9c1c-f08c20f82920.jpg)

Is there something that works like NEURON's `passive.mod`:

```
TITLE passive membrane channel

UNITS {
	(mV) = (millivolt)
	(mA) = (milliamp)
	(S) = (siemens)
}

NEURON {
	SUFFIX pas
	NONSPECIFIC_CURRENT i
	RANGE g, e
}

PARAMETER {
	g = .001	(S/cm2)	<0,1e9>
	e = -70	(mV)
}

ASSIGNED {v (mV)  i (mA/cm2)}

BREAKPOINT {
	i = g*(v - e)
}
```

**Comment by sg-s** [comment] 2018-12-14 13:10
looks like there is a lot to unpack here. first: https://github.com/sg-s/xolotl/issues/302#issuecomment-447211995

these two statements are exactly equivalent:

```
x.soma.add('Leak', 'gbar', gLeak, 'E', eLeak);
x.soma.add('conductance', 'Leak', 'gbar', gLeak, 'E', eLeak);
```
do you get different results (for the voltage dynamics) if you use these different syntaxes? if so, this is a bug. I see exactly the same behaviour.

**Comment by sg-s** [comment] 2018-12-14 13:15
then, this: https://github.com/sg-s/xolotl/issues/302#issuecomment-447212878

what do you mean "Leak does not pass current"? it most certainly does:

```
xolotl.go_to_examples
demo_bursting_neuron
x.output_type = 1;
results = x.integrate;
plot(results.AB.Leak.I)
```

gives you:

<img width="1172" alt="screen shot 2018-12-14 at 08 14 20" src="https://user-images.githubusercontent.com/6005346/50005424-4a269100-ff78-11e8-93b9-4e8968b9fecb.png">

which is the leak current. 

If you look at the C++ code for the Leak channel, you will see that it is exactly the same as the NEURON code you pasted.

**Comment by luadam4c** [comment] 2018-12-14 20:59
Ok, just making sure about the Leak current.

So I do seem to get different objects when I use the different syntaxes.

If I use this syntax:

```
x.soma.add('Leak', 'gbar', gLeak, 'E', eLeak);
x.dend1.add('Leak', 'gbar', gLeak, 'E', eLeak);
x.dend2.add('Leak', 'gbar', gLeak, 'E', eLeak);
```

I get:

> xolotl object with 
> ---------------------
> + dend1  
>   > Leak (g=3.6, E=-75)
> ---------------------
> + dend2  
>   > Leak (g=3.6, E=-75)
> ---------------------
> + soma  
>   > Leak (g=3.6, E=-75)
> ---------------------

> x.soma
> 
>  compartment object (9f24f53) with:
> 
>               vol : NaN
>          tree_idx : NaN
>   shell_thickness : 0.0001
>               len : 0.0261187839622344
>                Ca : 0.24
>        neuron_idx : NaN
>        Ca_average : NaN
>            Ca_out : 2000
>         Ca_target : NaN
>                Cm : 8.8
>            radius : 0.0130593919811172
>                 V : -60
>                 A : 0.0628
>              Leak : Leak object

> x.dend1
> 
>  compartment object (9f24f53) with:
> 
>               vol : NaN
>            Ca_out : 2000
>         Ca_target : NaN
>               len : 0.00713586296918925
>                Ca : 0.24
>                Cm : 8.8
>   shell_thickness : 0.0001
>        neuron_idx : NaN
>            radius : 0.00341524719193506
>        Ca_average : NaN
>          tree_idx : NaN
>                 V : -60
>                 A : 0.0628
>              Leak : Leak object
>         Axialsoma : Axial object

> x.dend2
> 
>  compartment object (9f24f53) with:
> 
>               vol : NaN
>            Ca_out : 2000
>         Ca_target : NaN
>               len : 0.00713586296918925
>                Ca : 0.24
>                Cm : 8.8
>   shell_thickness : 0.0001
>        neuron_idx : NaN
>            radius : 0.00341524719193506
>        Ca_average : NaN
>          tree_idx : NaN
>                 V : -60
>                 A : 0.0628
>              Leak : Leak object
>        Axialdend1 : Axial object

And I get this for the voltage clamp:

![test_voltage_clamp1](https://user-images.githubusercontent.com/36715881/50026122-c4c1d180-ffb5-11e8-867e-6f522a6e5750.jpg)

On the other hand, if I use this syntax:

```
x.soma.add('conductance', 'Leak', 'gbar', gLeak, 'E', eLeak);
x.dend1.add('conductance', 'Leak', 'gbar', gLeak, 'E', eLeak);
x.dend2.add('conductance', 'Leak', 'gbar', gLeak, 'E', eLeak);
```

I get:

> xolotl object with 
> ---------------------
> + dend1  
>   > conductance (g=3.6, E=-75)
> ---------------------
> + dend2  
>   > conductance (g=3.6, E=-75)
> ---------------------
> + soma  
>   > conductance (g=3.6, E=-75)
> ---------------------

> x.soma
> 
>  compartment object (9f24f53) with:
> 
>               vol : NaN
>            Ca_out : 2000
>   shell_thickness : 0.0001
>        Ca_average : NaN
>            radius : 0.0130593919811172
>                Ca : 0.24
>        neuron_idx : NaN
>          tree_idx : NaN
>                Cm : 8.8
>         Ca_target : NaN
>               len : 0.0261187839622344
>                 V : -60
>                 A : 0.0628
>       conductance : Leak object

> x.dend1
> 
>  compartment object (9f24f53) with:
> 
>        neuron_idx : NaN
>               vol : NaN
>   shell_thickness : 0.0001
>        Ca_average : NaN
>            Ca_out : 2000
>                Ca : 0.24
>          tree_idx : NaN
>            radius : 0.00341524719193506
>               len : 0.00713586296918925
>                Cm : 8.8
>                 V : -74.6946849244246
>         Ca_target : NaN
>                 A : 0.0628
>       conductance : Leak object
>         Axialsoma : Axial object
> 

> x.dend2
> 
>  compartment object (9f24f53) with:
> 
>        neuron_idx : NaN
>               vol : NaN
>   shell_thickness : 0.0001
>        Ca_average : NaN
>            Ca_out : 2000
>                Ca : 0.24
>          tree_idx : NaN
>            radius : 0.00341524719193506
>               len : 0.00713586296918925
>                Cm : 8.8
>                 V : -74.6946849244246
>         Ca_target : NaN
>                 A : 0.0628
>       conductance : Leak object
>        Axialdend1 : Axial object
> 

And I get this for the voltage clamp:

![test_voltage_clamp2](https://user-images.githubusercontent.com/36715881/50026272-503b6280-ffb6-11e8-9447-96f400daff6f.jpg)

I also noted that in the previous case, you can use this syntax to get the reversal potential:

```
leakReversal = x.(compToPatch).get('Leak.E');
```

However, in the latter case, you have to use this syntax to get the reversal potential:

```
leakReversal = x.(compToPatch).get('conductance.E');
```

Finally, another important issue I have is I have been trying to clamp the soma at **-65 mV**. Do I have the axial resistivity's units wrong? I was trying to use **173 Ohm cm**, which is converted to 1.73 MOhm mm per [this page](https://xolotl.readthedocs.io/en/master/reference/units/). But it seems so large that the voltage clamp is not influencing dendrite 1 and dendrite 2 much. I don't think the -74.69 is current in dendrites 1 and 2, it looks more like the slightly altered membrane potential instead. Furthermore, if it was the effect of axial resistivity, wouldn't dendrite 2 be influenced less than dendrite 1? But they seem to have the exact same values.

**Comment by sg-s** [comment] 2018-12-14 21:44
can you paste here the script which goes from 0 to setting up the model where it explodes, and where you use the different syntax? I want to reproduce exactly what you're trying to do

**Comment by sg-s** [comment] 2018-12-14 22:10
@luadam4c i think you have discovered behaviour that should not exist in cpplab. Specifically:

```
x.dend2.add('conductance', 'Leak', 'gbar', gLeak, 'E', eLeak);
```

should not work the way it works now, and will be removed soon. 

But the thing that pops out most is you should not name your Leak conductance "conductance", which is the name of a C++ class.

**Comment by sg-s** [comment] 2018-12-14 22:16
OK, the issue is that you're able to do this at all. I tried to voltage clamp a single compartment in tghe multi-compartment demo, and got this error:

```
Error using X_06704b14d544cd4fb12aaf764fd63d81
[xolotl] multi-compartment models cannot be integrated when something is clamped
yet.
```

So the question is how you're even able to do this without tripping this guard, because you are explicitly prevented from doing this.

**Comment by luadam4c** [comment] 2018-12-14 22:44
I tried saving the xolotl objects, reloading and redoing the plots, and now I get the same results across all compartments, with no convergence in the former syntax and convergence in the latter syntax. Are there other variables in the environment that can influence x.plot()? Why am I getting different results while saving it?

Former syntax:

![test_voltage_clamp1-1](https://user-images.githubusercontent.com/36715881/50033676-8c2af380-ffc7-11e8-9169-414cad005de4.jpg)

Latter syntax (note I wasn't trying to name the Leak object as 'conductance', I was just trying to emulate the way you add compartments per [this page](https://xolotl.readthedocs.io/en/master/reference/xolotl-methods/#add). Perhaps the documentation could be more clear that the first argument is the compartment name in this case.):

![test_voltage_clamp2-1](https://user-images.githubusercontent.com/36715881/50033680-8fbe7a80-ffc7-11e8-8e74-d90a9c8609a2.jpg)

Yes, I realized that the leak currents aren't doing anything at all in the voltage clamp mode. -74.69 mV is what I set the initial V at for all compartments.

You can get the xolotl objects to test with here:

[voltage_clamp_leak_syntax.zip](https://github.com/sg-s/xolotl/files/2681917/voltage_clamp_leak_syntax.zip)

The only thing I did for the above two figures is to load a file and type

```
testObject.plot()
```

**Comment by sg-s** [comment] 2018-12-14 22:49
both objects yield the same result, with flat voltages -- is this not what you expect?

**Comment by sg-s** [comment] 2018-12-14 22:52
BTW you have only two synapses in your model -- remember that you need synapses both ways, so you need a pair of synapses to connect soma to dend1. Every synapse is a one-way synapse

**Comment by sg-s** [comment] 2018-12-14 22:53
but this does confirm the bug where xolotl allows you to integrate it -- it shouldn't

**Comment by sg-s** [comment] 2018-12-14 22:55
OK, the reason it allows you to integrate it is that it doesn't think it's a multi-compartment model -- because you haven't wired up the synapses correctly. See this [example file](https://github.com/sg-s/xolotl/blob/master/examples/demo_multi_compartment.m) to see how to connect different parts of a neuron

**Comment by luadam4c** [comment] 2018-12-14 23:04
> OK, the reason it allows you to integrate it is that it doesn't think it's a multi-compartment model -- because you haven't wired up the synapses correctly. See this [example file](https://github.com/sg-s/xolotl/blob/master/examples/demo_multi_compartment.m) to see how to connect different parts of a neuron

Thanks for the tip. Can you perhaps explain the x.connect syntax for the 'Axial' synapse? I can't find anywhere in this piece of code where 'axial_resitivity' is actually used (it's also spelled wrong).

Do I just have to connect both ways manually? Why not make this automatic for the 'Axial' type of synapse?

This is what I was doing before:

```
x.connect('soma', 'dend1', 'Axial', 'resistivity', axialResistivity);
x.connect('dend1', 'dend2', 'Axial', 'resistivity', axialResistivity);
```

**Comment by sg-s** [comment] 2018-12-14 23:14
the `Axial` synapse has a `resistivity` parameter that takes on the default value of .001 (the textbook value). 

So if you want to connect your three compartments, you need:

```
x.connect('soma', 'dend1', 'Axial', 'resistivity', 1e-3);
x.connect('dend1', 'dend2', 'Axial', 'resistivity', 1e-3);
x.connect('dend2', 'dend1', 'Axial', 'resistivity', 1e-3);
x.connect('dend1', 'soma', 'Axial', 'resistivity', 1e-3);
```

All synapses are treated as one-way, which is why if you want a two-way synapse, you need to connect it both ways. 

`xolotl.slice()` automatically configures two-way Axial synapses between compartments

**Comment by luadam4c** [comment] 2018-12-14 23:14
> both objects yield the same result, with flat voltages -- is this not what you expect?

I realized when I saved the xolotl object using this syntax:

```
save('/media/adamX/xolotl_test/voltage_clamp_leak_syntax2.mat', 'testObject');
```

The properties `I_ext`, `V_clamp` are not saved (not the default either, both become empty!)

Why is that?

**Comment by sg-s** [comment] 2018-12-14 23:16
very strange. you're right, that shouldn't happen

**Comment by luadam4c** [comment] 2018-12-14 23:18
> the `Axial` synapse has a `resistivity` parameter that takes on the default value of .001 (the textbook value).
> 
> So if you want to connect your three compartments, you need:
> 
> ```
> x.connect('soma', 'dend1', 'Axial', 'resistivity', 1e-3);
> x.connect('dend1', 'dend2', 'Axial', 'resistivity', 1e-3);
> x.connect('dend2', 'dend1', 'Axial', 'resistivity', 1e-3);
> x.connect('dend1', 'soma', 'Axial', 'resistivity', 1e-3);
> ```
> All synapses are treated as one-way, which is why if you want a two-way synapse, you need to connect it both ways.
> 
> `xolotl.slice()` automatically configures two-way Axial synapses between compartments

I understand what you are saying, but is it possible to make x.connect() symmetrical when 'Axial' is selected for the synapse type? It will cause less confusion and prevent errors in using the 'Axial' type in the future. There is no circumstance where you would want a one-way 'Axial' synapse, right? Perhaps you can add this as an enhancement.

**Comment by sg-s** [comment] 2018-12-14 23:33
> > the `Axial` synapse has a `resistivity` parameter that takes on the default value of .001 (the textbook value).
> > So if you want to connect your three compartments, you need:
> > ```
> > x.connect('soma', 'dend1', 'Axial', 'resistivity', 1e-3);
> > x.connect('dend1', 'dend2', 'Axial', 'resistivity', 1e-3);
> > x.connect('dend2', 'dend1', 'Axial', 'resistivity', 1e-3);
> > x.connect('dend1', 'soma', 'Axial', 'resistivity', 1e-3);
> > ```
> > All synapses are treated as one-way, which is why if you want a two-way synapse, you need to connect it both ways.
> > `xolotl.slice()` automatically configures two-way Axial synapses between compartments
> 
> I understand what you are saying, but is it possible to make x.connect() symmetrical when 'Axial' is selected for the synapse type? It will cause less confusion and prevent errors in using the 'Axial' type in the future. There is no circumstance where you would want a one-way 'Axial' synapse, right? Perhaps you can add this as an enhancement.

OK, see #306

**Comment by sg-s** [comment] 2018-12-15 01:21
ok, fixed!

**Comment by luadam4c** [comment] 2018-12-15 01:30
> 
> can you send me a script that generates the model you want, so that I can run that script?

I moved the dependent code to a second server, installed the xolotl version from 12-Dec-2018 and retried it. I got the same thing you got. Sorry I didn't think of trying this earlier.

Therefore I went back to the first server and uninstalled xolotl from MATLAB's Add-Ons Manager. I apologize that I didn't do this before, but that was because when I tried clicking on the Add-Ons Manager nothing showed up. But after some googling that was fixed with [this solution](https://www.mathworks.com/matlabcentral/answers/373121-get-more-apps-doesn-t-work). 

And then I reinstalled xolotl on the first server and then got the same thing you got. So I think older versions of xolotl was interfering with the simulations. Sorry about taking so long to get to this and thanks for your input.

For completeness, here are the files I'm using to do the simulations:
[xolotl_test.zip](https://github.com/sg-s/xolotl/files/2682255/xolotl_test.zip)

For quick access to what each function does, see this page:
https://blabuva.github.io/Adams_Functions/

I'm generating the model by running the script:
```
m3ha_xolotl_test
```

**Comment by sg-s** [comment] 2018-12-15 15:40
> Therefore I went back to the first server and uninstalled xolotl from MATLAB's Add-Ons Manager. I apologize that I didn't do this before, but that was because when I tried clicking on the Add-Ons Manager nothing showed up. But after some googling that was fixed with this solution.

looks like you found a bug in MATLAB with their add-on manager. ouch. 

> And then I reinstalled xolotl on the first server and then got the same thing you got. So I think older versions of xolotl was interfering with the simulations.

sounds to me that what we need is a robust way of verifying that we're on the same version -- i'll think of how this can be implemented. 

I ran your m3ha model, and see this:

<img width="1312" alt="screen shot 2018-12-15 at 10 40 33" src="https://user-images.githubusercontent.com/6005346/50044717-e5d9ff00-0055-11e9-9b72-b87c600e00d9.png">

**Comment by luadam4c** [comment] 2018-12-17 16:21
> 
> I ran your m3ha model, and see this:
> 
> <img alt="screen shot 2018-12-15 at 10 40 33" width="1312" src="https://user-images.githubusercontent.com/6005346/50044717-e5d9ff00-0055-11e9-9b72-b87c600e00d9.png">

Yes, which makes me think that the compartments are not really connected yet. The current pulse response in the soma should have caused a voltage change in the dendrites as well. But maybe I'm doing something wrong. Can you post an updated release so I can try out the changes you have made to the Axial synapse?

**Comment by sg-s** [comment] 2018-12-17 17:56
just uploaded a new release.

BTW since you're familiar with git, you should probably not use the toolbox since it is (by design) meant to be a slow, stable release channel. if you clone this repo, cpplab, and the mtools dep., everything should work 

see: https://xolotl.readthedocs.io/en/master/how-to/install-configure/#install-using-git

**Comment by luadam4c** [comment] 2018-12-20 03:11
> just uploaded a new release.
> 
> BTW since you're familiar with git, you should probably not use the toolbox since it is (by design) meant to be a slow, stable release channel. if you clone this repo, cpplab, and the mtools dep., everything should work
> 
> see: https://xolotl.readthedocs.io/en/master/how-to/install-configure/#install-using-git

Just did! I've also added them as submodules so I will be able to update them altogether easily in the future.

**Comment by luadam4c** [comment] 2018-12-20 03:12
> > I ran your m3ha model, and see this:
> > <img alt="screen shot 2018-12-15 at 10 40 33" width="1312" src="https://user-images.githubusercontent.com/6005346/50044717-e5d9ff00-0055-11e9-9b72-b87c600e00d9.png">
> 
> Yes, which makes me think that the compartments are not really connected yet. The current pulse response in the soma should have caused a voltage change in the dendrites as well. But maybe I'm doing something wrong. Can you post an updated release so I can try out the changes you have made to the Axial synapse?

Any updates on this? I still don't see any change in the dendritic response when I inject only in the soma.

**Comment by sg-s** [comment] 2018-12-20 14:20
OK, the problem is: you have a mulit-compartment model, and injecting current in one compartment doesn't do anything in the other compartments? OK, let me take a look

**Comment by sg-s** [comment] 2018-12-20 14:41
OK, this is the issue:

and unimplemented line [here](https://github.com/sg-s/xolotl/blob/e83d02ebd872a2212e370bce8bdba551b68f8bc0/c%2B%2B/compartment.hpp#L451)

I was being lazy.

**Comment by sg-s** [comment] 2018-12-20 15:50
@luadam4c should be fixed.

if you see the voltages exploding, then the most likely explanation is you're injecting too much current. 

This worked for me:

```
xolotl.go_to_examples
xolotl.cleanup;
demo_multi_compartment
close all

x.I_ext = zeros(1,11);
I_ext = x.integrate;
I_ext = 0*I_ext;
I_ext(1e4:1.5e4,1) = .1;
x.I_ext = I_ext;
x.set('*HCurrent*gbar',0)
V = x.integrate;
plot(V(:,1))
```

**Comment by luadam4c** [comment] 2018-12-20 16:33
> @luadam4c should be fixed.
> 
> if you see the voltages exploding, then the most likely explanation is you're injecting too much current.
> 
> This worked for me:
> 
> ```
> xolotl.cleanup;
> 
> 
> demo_multi_compartment
> close all
> 
> x.I_ext = zeros(1,11);
> I_ext = x.integrate;
> I_ext = 0*I_ext;
> I_ext(1e4:1.5e4,1) = .004;
> x.I_ext = I_ext;
> x.set('*HCurrent*gbar',0)
> x.set('*NaV*gbar',0)
> V = x.integrate;
> 
> 
> figure, hold on
> subplot(2,1,1); hold on
> plot(V(:,1))
> 
> subplot(2,1,2); hold on
> plot(V(:,2))
> ```
> and i see this:
> 
> ![screen shot 2018-12-20 at 10 53 51 am](https://user-images.githubusercontent.com/6005346/50295207-8f016a80-0445-11e9-9982-0bde852be3e9.png)

I got that too. But isn't that because your demo_multi_compartment.m is actually treating soma and axon as different cells connected with an electrical synapse?

If I change this line of code in demo_multi_compartment.m:
```
x.connect('Neurite01','CellBody');
```
to
```
x.connect('Neurite01','CellBody', 'Axial');
```

This is the response to your code above:
![test_demo_multi_compartment2](https://user-images.githubusercontent.com/36715881/50297394-b27ae400-044a-11e9-844f-487d0388f55b.jpg)

**Comment by sg-s** [comment] 2018-12-20 16:41
> But isn't that because your demo_multi_compartment.m is actually treating soma and axon as different cells connected with an electrical synapse?

No, compartments are connected using `Axial` synapses:

```
x.find('Axial')
ans =
  20×1 cell array
    {'CellBody.AxialNeurite01' }
    {'Neurite01.AxialCellBody' }
    {'Neurite01.AxialNeurite02'}
    {'Neurite02.AxialNeurite01'}
    {'Neurite02.AxialNeurite03'}
    {'Neurite03.AxialNeurite02'}
    {'Neurite03.AxialNeurite04'}
    {'Neurite04.AxialNeurite03'}
    {'Neurite04.AxialNeurite05'}
    {'Neurite05.AxialNeurite04'}
    {'Neurite05.AxialNeurite06'}
    {'Neurite06.AxialNeurite05'}
    {'Neurite06.AxialNeurite07'}
    {'Neurite07.AxialNeurite06'}
    {'Neurite07.AxialNeurite08'}
    {'Neurite08.AxialNeurite07'}
    {'Neurite08.AxialNeurite09'}
    {'Neurite09.AxialNeurite08'}
    {'Neurite09.AxialNeurite10'}
    {'Neurite10.AxialNeurite09'}
```

> If I change this line of code in demo_multi_compartment.m...

WTF. Weird, let me look...

**Comment by sg-s** [comment] 2018-12-20 16:45
> But isn't that because your demo_multi_compartment.m is actually treating soma and axon as different cells connected with an electrical synapse?

No, they're connected using Axial synapses.

See for yourself:

```
x.find('Axial')
 20×1 cell array
    {'CellBody.AxialNeurite01' }
    {'Neurite01.AxialCellBody' }
    {'Neurite01.AxialNeurite02'}
    {'Neurite02.AxialNeurite01'}
    {'Neurite02.AxialNeurite03'}
    {'Neurite03.AxialNeurite02'}
    {'Neurite03.AxialNeurite04'}
    {'Neurite04.AxialNeurite03'}
    {'Neurite04.AxialNeurite05'}
    {'Neurite05.AxialNeurite04'}
    {'Neurite05.AxialNeurite06'}
    {'Neurite06.AxialNeurite05'}
    {'Neurite06.AxialNeurite07'}
    {'Neurite07.AxialNeurite06'}
    {'Neurite07.AxialNeurite08'}
    {'Neurite08.AxialNeurite07'}
    {'Neurite08.AxialNeurite09'}
    {'Neurite09.AxialNeurite08'}
    {'Neurite09.AxialNeurite10'}
    {'Neurite10.AxialNeurite09'}
```

That's because `x.connect('Neurite01','CellBody');` is not the same as `x.connect('Neurite01','CellBody', 'Axial');` ! The first one sets up *TWO* axial synapses, while the second command sets up a one-directional Axial synapse. If you want to connect two components in a mulit-compartment neuron, you want to use the first one.

**Comment by sg-s** [comment] 2018-12-20 16:47
to be clear, if you use `x.connect('Neurite01','CellBody','Axial')`, you're missing a synapse:

```
  19×1 cell array
    {'CellBody.AxialNeurite01' }
    {'Neurite01.AxialNeurite02'}
    {'Neurite02.AxialNeurite01'}
    {'Neurite02.AxialNeurite03'}
    {'Neurite03.AxialNeurite02'}
    {'Neurite03.AxialNeurite04'}
    {'Neurite04.AxialNeurite03'}
    {'Neurite04.AxialNeurite05'}
    {'Neurite05.AxialNeurite04'}
    {'Neurite05.AxialNeurite06'}
    {'Neurite06.AxialNeurite05'}
    {'Neurite06.AxialNeurite07'}
    {'Neurite07.AxialNeurite06'}
    {'Neurite07.AxialNeurite08'}
    {'Neurite08.AxialNeurite07'}
    {'Neurite08.AxialNeurite09'}
    {'Neurite09.AxialNeurite08'}
    {'Neurite09.AxialNeurite10'}
    {'Neurite10.AxialNeurite09'}
```

see -- only 19?

**Comment by luadam4c** [comment] 2018-12-20 18:07
> > But isn't that because your demo_multi_compartment.m is actually treating soma and axon as different cells connected with an electrical synapse?
> 
> No, they're connected using Axial synapses.
> 
> See for yourself:
> 
> ```
> x.find('Axial')
>  20×1 cell array
>     {'CellBody.AxialNeurite01' }
>     {'Neurite01.AxialCellBody' }
>     {'Neurite01.AxialNeurite02'}
>     {'Neurite02.AxialNeurite01'}
>     {'Neurite02.AxialNeurite03'}
>     {'Neurite03.AxialNeurite02'}
>     {'Neurite03.AxialNeurite04'}
>     {'Neurite04.AxialNeurite03'}
>     {'Neurite04.AxialNeurite05'}
>     {'Neurite05.AxialNeurite04'}
>     {'Neurite05.AxialNeurite06'}
>     {'Neurite06.AxialNeurite05'}
>     {'Neurite06.AxialNeurite07'}
>     {'Neurite07.AxialNeurite06'}
>     {'Neurite07.AxialNeurite08'}
>     {'Neurite08.AxialNeurite07'}
>     {'Neurite08.AxialNeurite09'}
>     {'Neurite09.AxialNeurite08'}
>     {'Neurite09.AxialNeurite10'}
>     {'Neurite10.AxialNeurite09'}
> ```
> That's because `x.connect('Neurite01','CellBody');` is not the same as `x.connect('Neurite01','CellBody', 'Axial');` ! The first one sets up _TWO_ axial synapses, while the second command sets up a one-directional Axial synapse. If you want to connect two components in a mulit-compartment neuron, you want to use the first one.

1. I thought you said the default for x.connect is an electrical synapse. So if I connect a cell to another cell through an electrical synapse, what would I use? 

2. I cannot find how you actually set the axial resistivity in your code. Note that the variable axial_resitivity is not used anywhere. How can you set it for x.slice and x.connect without the 'Axial' argument?

3. Also, it seems like x.slice must be used for xolotl to consider a model multi-compartment. If I create three compartments, 'soma', 'dend1', 'dend2' and do something like:

```
x.connect('soma', 'dend1', 'Axial', 'resistivity', 1);
x.connect('dend1', 'soma', 'Axial', 'resistivity', 1);
x.connect('dend1', 'dend2', 'Axial', 'resistivity', 1);
x.connect('dend2', 'dend1', 'Axial', 'resistivity', 1);
```

Then I can't get it to work. Can you provide an example of a three compartment model example where x.slice is not used? This will be important if each compartment has a different radius.

**Comment by sg-s** [comment] 2018-12-20 18:55
1. no, connect uses `Axial` synapses, as it says [here](https://xolotl.readthedocs.io/en/master/reference/xolotl-methods/#connect)
2. at any point, you can change any parameter. don't know what parameters you can change? you can look directly -- so `x.CellBody.AxialNeurite01` shows you:

```
ans = 

 Axial object (9a3572e) with:

   resistivity : 0.001
          gmax : 312.256049960968
```

so you see resistivity is a parameter of the Axial synapse. You can set it using any way you want (directly, using the `set` command, etc). 

3. Shit, you're totally right -- what I forgot to mention all this time is the `tree_idx` parameter, which allows xolotl to work out which multi-compartment model is which. Note that in the demo, `tree_idx` is set to 0 for the cell_body. I'll update the documentation to point this out

**Closed** 2018-12-20 19:13 UTC
Labels: documentation

**Comment by sg-s** [comment] 2018-12-20 19:16
updated docs with info about tree_idx here:

https://xolotl.readthedocs.io/en/master/how-to/create-multi-compartment-models/

**Comment by sg-s** [comment] 2018-12-21 13:19
> Thanks. That's useful. So tree_idx means the idx for the cell or the position in the tree? Does it mean anything to set a tree_idx for the other compartments?

if you're setting up a cable, you can set the tree_idx of the soma to 0 to identify it as such, and the other tree_idxs are computed automatically (network::resolveTree()) does this
